# Generated by Django 5.1.6 on 2025-03-21 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_is_sale_product_has_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sale_price',
            new_name='discounted_price',
        ),
    ]
