# Generated by Django 5.1.6 on 2025-04-25 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_sale_price_product_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
