# Generated by Django 5.1.6 on 2025-04-26 13:14

from django.db import migrations

def forwards_func(apps, schema_editor):
    Product = apps.get_model('store', 'Product')
    Product.objects.filter(description__isnull=True).update(description='')

class Migration(migrations.Migration):
    dependencies = [
        ('store', '0009_alter_product_description'),
    ]
    
    operations = [
        migrations.RunPython(forwards_func),
    ]